[package]
name = "wok"
version = "0.3.0-dev"
authors = ["Serge Matveenko <lig@countzero.co>"]
edition = "2018"

[dependencies]
git2 = "0.13.14"
serde = { version = "1.0.118", features = ["derive"] }
serde_yaml = "0.8.14"
clap = "3.0.0-beta.2"

[dev-dependencies]
assert_fs = "1.0.0"
pretty_assertions = "0.6.1"
rstest = "0.6.4"
