[project]
name = "wok-docs"
version = "1.0.2"
description = ""
authors = [
    {name = "Serge Matveenko", email = "lig@countzero.co"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mkdocs-material>=9.2.4",
    "mdx-truly-sane-lists>=1.3",
]
